// config.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.18-Prod

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE EXCSB1_WITH_EX8874
#define OLED_DRIVER 128,64
#define WIFI_HOSTNAME "dccex"
#define WIFI_SSID "ingold"
#define WIFI_PASSWORD "faithisgood08"
#define ENABLE_WIFI true
#define WIFI_CHANNEL 1
#define DISABLE_EEPROM
// GPIO 33 on EX-CSB1
#define WIFI_LED 33
